# 排序算法

### 1.冒泡排序

* 它重复地走访要排序的数列，一次比较两个元素，如果他们的顺序错误就把他们交换过来

In [1]:
def bubble_sort(arr):
    lens = len(arr)
    for i in range(lens):
        for j in range(lens-1):
            if arr[j+1] < arr[j]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
    return arr

import numpy as np
arr = np.random.randint(0, 10, 10)
bubble_sort(arr)

array([3, 4, 5, 5, 6, 7, 8, 8, 8, 9])

### 2.选择排序

* 每次选出最小的元素放在未排序队列后面

In [2]:
def select_sort(arr):
    lens = len(arr)
    for i in range(lens-1):
        for j in range(i+1, lens):
            if arr[j] < arr[i]:
                arr[j], arr[i] = arr[i], arr[j]
                
    return arr
arr = np.random.randint(0, 10, 10)
select_sort(arr)

array([0, 0, 0, 3, 3, 4, 6, 6, 8, 8])

### 3.插入排序

* 把数据插入已经排序的数据中

In [3]:
def insert_sort(arr):
    lens = len(arr)
    for i in range(1, lens):
        cur = arr[i]
        len_sorted = i
        while cur < arr[len_sorted-1]:
            arr[len_sorted] = arr[len_sorted-1]
            len_sorted -= 1
            if len_sorted - 1 < 0:
                break
        arr[len_sorted] = cur
    return arr

arr = np.random.randint(0, 10, 10)
insert_sort(arr)

array([0, 1, 1, 2, 3, 3, 4, 4, 5, 8])

### 4.希尔排序

* 插入排序的高效实现，先切分为不同的片段，片段内部再用插入排序，按步长合并，最后合并所有片段

In [4]:
def shell_sort(arr, step=3, groups=3):
    lens = len(arr)
    
    while groups > 0:
        start = 0
        each_group = lens // groups
        while start < lens:
            end = each_group + start

            arr[start: end] = insert_sort(arr[start: end])
            start = end
            
        groups = groups // step
    return arr
arr = np.random.randint(0, 10, 10)
shell_sort(arr)

array([0, 1, 1, 1, 2, 2, 3, 5, 6, 7])

### 5.归并排序

* 分治法：先使每个子序列有序，再使子序列段间有序

In [5]:
def merge(left, right):
    res = []
    i = j = 0
    while i < len(left) and j < len(right):
        if left[i] <= right[j]:
            res.append(left[i])
            i += 1
        else:
            res.append(right[j])
            j += 1
    res.extend(left[i: ])
    res.extend(right[j: ])
    return res
    
def merge_sort(arr):
    if len(arr) == 0:
        return None
    if len(arr) == 1:
        return arr
    
    mid = len(arr) // 2
    left = merge_sort(arr[0: mid])
    right = merge_sort(arr[mid: ])
    
    return merge(left, right)

arr = np.random.randint(0, 10, 10)
merge_sort(arr)

[3, 4, 4, 5, 6, 6, 6, 6, 7, 9]

### 6.快速排序

* 快速排序算法是一种基于交换的高效的排序算法，是最快的排序算法之一，它采用了 分治法的思想

In [6]:
def quick_sort(arr, left, right):
    if left >= right:
        return
    low = left
    high = right
    pivot = arr[low]
    while left < right:
        while left < right and arr[right] > pivot:
            right -= 1
        arr[left] = arr[right]
        while left < right and arr[left] <= pivot:
            left += 1
        arr[left], arr[right] = arr[right], arr[left]
    arr[right] = pivot
    quick_sort(arr, low, left - 1)
    quick_sort(arr, left + 1, high)
    return arr

arr = np.random.randint(0, 10, 10)
quick_sort(arr, 0, len(arr)-1)

array([1, 1, 2, 2, 3, 4, 5, 6, 6, 9])

### 7.堆排序

* 建立大根堆或小根堆进行排序

In [24]:
def heap_shift(arr, parent, lens):
    lchild = 2 * parent
    rchild = 2 * parent + 1
    max_index = parent

    if parent < lens//2:
        if lchild < lens and arr[lchild] > arr[max_index]:
            max_index = lchild

        if rchild < lens and arr[rchild] > arr[max_index]:
            max_index = rchild

        if max_index is not parent:
            arr[parent], arr[max_index] = arr[max_index], arr[parent]
            heap_shift(arr, max_index, lens)

def build_heap(arr, lens):
    for parent in range(lens//2)[::-1]:
        heap_shift(arr, parent, lens)
    return arr

def heap_sort(arr):
    lens = len(arr)
    arr = build_heap(arr, lens)
    for i in range(0, lens)[::-1]:
        arr[0], arr[i] = arr[i], arr[0]
        heap_shift(arr, 0, i)

    return arr

arr = np.random.randint(0, 10, 10)
heap_sort(arr)

array([0, 1, 1, 3, 3, 4, 5, 7, 9, 9])

### 8.计数排序

* 输入数据的范围在 [0,N-1] 之间，则可以开辟一个大小为 N 的数组空间，将输入的数据值转化为键存储在该数组空间中，数组中的元素为该元素出现的个数

In [31]:
def count_sort(arr):

    bucket = [0] * (max(arr) + 1)
    for num in arr:  
        bucket[num] += 1
    i = 0  
    for j in range(len(bucket)):
        while bucket[j] > 0:
            arr[i] = j
            bucket[j] -= 1
            i += 1
    return arr

arr = np.random.randint(0, 10, 10)
count_sort(arr)

array([0, 4, 5, 6, 6, 6, 6, 7, 9, 9])

### 9.桶排序

* 桶排序是计数排序的升级版。它利用了函数的映射关系，高效与否的关键就在于这个映射函数的确定。

In [35]:
def bucket_sort(arr, BucketSize = 5):
    maxVal, minVal = max(arr), min(arr)
    bucketSize = BucketSize 
    bucketCount = (maxVal - minVal) // bucketSize + 1
    buckets = []  
    for i in range(bucketCount):
        buckets.append([])
        
    for num in arr:
        buckets[(num - minVal) // bucketSize].append(num)
    arr = []
    
    for bucket in buckets:
        insert_sort(bucket) # 桶内排序
        arr.extend(bucket) 
    return arr

arr = np.random.randint(0, 10, 10)
bucket_sort(arr)

[1, 1, 3, 4, 5, 6, 9, 9, 9, 9]

### 10.基数排序

* 先排序个位数，再依次排序十位数，百位数

In [41]:
def radix_sort(arr):
    mod = 10
    div = 1
    mostBit = len(str(max(arr)))
    buckets = [[] for row in range(mod)]
    while mostBit:
        for num in arr:  
            buckets[num // div % mod].append(num)
        i = 0 
        for bucket in buckets: 
            while bucket:
                arr[i] = bucket.pop(0)
                i += 1
        div *= 10
        mostBit -= 1
    return arr

arr = np.random.randint(0, 100, 10)
radix_sort(arr)

array([ 0,  1,  2,  6, 34, 44, 53, 66, 68, 90])